Test new CI file

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,7 +3,29 @@ on: [push, pull_request]
 
 jobs:
   test:
-    runs-on: 'ubuntu-latest'
+    runs-on: ubuntu-22.04
+
+    services:
+      postgres:
+        image: postgres:13
+        env:
+          POSTGRES_USER: 'postgres'
+          POSTGRES_HOST_AUTH_METHOD: 'trust'
+        ports:
+          - 5432:5432
+        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
+
+      mariadb:
+        image: mariadb:10
+        env:
+          MYSQL_USER: 'root'
+          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
+          MYSQL_CHARACTER_SET_SERVER: "utf8mb4"
+          MYSQL_COLLATION_SERVER: "utf8mb4_unicode_ci"
+        ports:
+          - 3306:3306
+        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3
+
     strategy:
       fail-fast: false
       matrix:
@@ -18,39 +40,18 @@ jobs:
             moodle-branch: 'MOODLE_403_STABLE'
             database: 'pgsql'
 
-    services:
-      postgres:
-        image: postgres
-        env:
-          POSTGRES_USER: 'postgres'
-          POSTGRES_HOST_AUTH_METHOD: 'trust'
-        options: >-
-          --health-cmd pg_isready
-          --health-interval 10s
-          --health-timeout 5s
-          --health-retries 3
-        ports:
-          - 5432:5432
-
-      mariadb:
-        image: mariadb:10
-        env:
-          MYSQL_USER: 'root'
-          MYSQL_ALLOW_EMPTY_PASSWORD: "true"
-        ports:
-          - 3306:3306
-        options: --health-cmd="mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 3
-
     steps:
       - name: Checkout
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
         with:
           path: plugin
 
-      - name: Install node
-        uses: actions/setup-node@v1
+      - name: Setup PHP
+        uses: shivammathur/setup-php@v2
         with:
-          node-version: ${{ matrix.node }}
+          php-version: ${{ matrix.php }}
+          extensions: ${{ matrix.extensions }}
+          ini-values: max_input_vars=5000 # Needed for PHP8.
 
       - name: Setup PHP
         uses: shivammathur/setup-php@v2
@@ -61,12 +62,14 @@ jobs:
 
       - name: Deploy moodle-plugin-ci
         run: |
-          composer create-project -n --no-dev --prefer-dist brickfield/moodle-plugin-ci ci ^4
+          composer create-project -n --no-dev --repository='{"type":"vcs","url":"https://github.com/brickfield/moodle-plugin-ci.git"}' brickfield/moodle-plugin-ci ci ^4
           # Add dirs to $PATH
           echo $(cd ci/bin; pwd) >> $GITHUB_PATH
           echo $(cd ci/vendor/bin; pwd) >> $GITHUB_PATH
-          # PHPUnit depends on en_AU.UTF-8 locale
           sudo locale-gen en_AU.UTF-8
+          # Install nvm.
+          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
+
       - name: Install Moodle
         # Need explicit IP to stop mysql client fail on attempt to use unix socket.
         run: |
@@ -75,46 +78,49 @@ jobs:
           DB: ${{ matrix.database }}
           MOODLE_BRANCH: ${{ matrix.moodle-branch }}
 
-      - name: phplint
-        if: ${{ always() }}
+      - name: PHP Lint
+        if: ${{ !cancelled() }}
         run: moodle-plugin-ci phplint
 
-      - name: phpcpd
-        if: ${{ always() }}
-        run: moodle-plugin-ci phpcpd || true
-
-      - name: phpmd
-        if: ${{ always() }}
+      - name: PHP Mess Detector
+        continue-on-error: true # This step will show errors but will not fail
+        if: ${{ !cancelled() }}
         run: moodle-plugin-ci phpmd
 
-      - name: codechecker
-        if: ${{ always() }}
-        run: moodle-plugin-ci codechecker
+      - name: Moodle Code Checker
+        if: ${{ !cancelled() }}
+        # run: moodle-plugin-ci phpcs --max-warnings 0
+        run: moodle-plugin-ci phpcs
 
       - name: Moodle PHPDoc Checker
-        if: ${{ always() }}
-        run: moodle-plugin-ci phpdoc
+        if: ${{ !cancelled() }}
+        run: moodle-plugin-ci phpdoc --max-warnings 0
 
-      - name: validate
-        if: ${{ always() }}
+      - name: Validating
+        if: ${{ !cancelled() }}
         run: moodle-plugin-ci validate
 
-      - name: savepoints
-        if: ${{ always() }}
+      - name: Check upgrade savepoints
+        if: ${{ !cancelled() }}
         run: moodle-plugin-ci savepoints
 
-      - name: mustache
-        if: ${{ always() }}
+      - name: Mustache Lint
+        if: ${{ !cancelled() }}
         run: moodle-plugin-ci mustache
 
-      - name: grunt
-        if: ${{ always() }}
-        run: moodle-plugin-ci grunt
+      - name: Grunt
+        if: ${{ !cancelled() }}
+        # run: moodle-plugin-ci grunt --max-lint-warnings 0
+        run: moodle-plugin-ci grunt -t ignorefiles -t rollup:dist -t gherkinlint --max-lint-warnings 0
 
-      - name: phpunit
-        if: ${{ always() }}
+      - name: PHPUnit tests
+        if: ${{ !cancelled() }}
         run: moodle-plugin-ci phpunit
 
-      - name: behat
-        if: ${{ always() }}
+      - name: Behat features
+        if: ${{ !cancelled() }}
         run: moodle-plugin-ci behat --profile chrome
+
+      - name: Mark cancelled jobs as failed.
+        if: ${{ cancelled() }}
+        run: exit 1
